package kkaimigrate

var riskSchemaStatements = map[string][]string{
	DialectSQLite: {
		`CREATE TABLE IF NOT EXISTS kkai_policy_incidents (
id INTEGER PRIMARY KEY AUTOINCREMENT,
event_id VARCHAR(128) NOT NULL UNIQUE,
input_sha256 CHAR(64) NOT NULL,
source VARCHAR(32) NOT NULL,
occurred_at BIGINT NOT NULL,
request_id VARCHAR(64) NOT NULL DEFAULT '',
user_id INTEGER NOT NULL DEFAULT 0,
token_id INTEGER NOT NULL DEFAULT 0,
channel_id INTEGER NOT NULL DEFAULT 0,
model_name VARCHAR(128) NOT NULL DEFAULT '',
rule_version VARCHAR(64) NOT NULL DEFAULT '',
evidence_sha256 CHAR(64) NOT NULL,
token_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
upstream_key_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
decision VARCHAR(32) NOT NULL,
metadata TEXT NOT NULL,
action_taken VARCHAR(255) NOT NULL DEFAULT '',
action_result VARCHAR(255) NOT NULL DEFAULT '',
token_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disable_skipped BOOLEAN NOT NULL DEFAULT FALSE,
channel_disabled BOOLEAN NOT NULL DEFAULT FALSE,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS kkai_outbox (
id INTEGER PRIMARY KEY AUTOINCREMENT,
event_key VARCHAR(192) NOT NULL UNIQUE,
topic VARCHAR(128) NOT NULL,
aggregate_id VARCHAR(128) NOT NULL DEFAULT '',
payload TEXT NOT NULL,
status VARCHAR(16) NOT NULL,
attempts INTEGER NOT NULL DEFAULT 0,
available_at BIGINT NOT NULL,
locked_at BIGINT NOT NULL DEFAULT 0,
locked_by VARCHAR(128) NOT NULL DEFAULT '',
last_error TEXT NOT NULL,
created_at BIGINT NOT NULL,
delivered_at BIGINT NOT NULL DEFAULT 0
)`,
	},
	DialectMySQL: {
		`CREATE TABLE IF NOT EXISTS kkai_policy_incidents (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
event_id VARCHAR(128) NOT NULL UNIQUE,
input_sha256 CHAR(64) NOT NULL,
source VARCHAR(32) NOT NULL,
occurred_at BIGINT NOT NULL,
request_id VARCHAR(64) NOT NULL DEFAULT '',
user_id INT NOT NULL DEFAULT 0,
token_id INT NOT NULL DEFAULT 0,
channel_id INT NOT NULL DEFAULT 0,
model_name VARCHAR(128) NOT NULL DEFAULT '',
rule_version VARCHAR(64) NOT NULL DEFAULT '',
evidence_sha256 CHAR(64) NOT NULL,
token_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
upstream_key_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
decision VARCHAR(32) NOT NULL,
metadata TEXT NOT NULL,
action_taken VARCHAR(255) NOT NULL DEFAULT '',
action_result VARCHAR(255) NOT NULL DEFAULT '',
token_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disable_skipped BOOLEAN NOT NULL DEFAULT FALSE,
channel_disabled BOOLEAN NOT NULL DEFAULT FALSE,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
		`CREATE TABLE IF NOT EXISTS kkai_outbox (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
event_key VARCHAR(192) NOT NULL UNIQUE,
topic VARCHAR(128) NOT NULL,
aggregate_id VARCHAR(128) NOT NULL DEFAULT '',
payload TEXT NOT NULL,
status VARCHAR(16) NOT NULL,
attempts INT NOT NULL DEFAULT 0,
available_at BIGINT NOT NULL,
locked_at BIGINT NOT NULL DEFAULT 0,
locked_by VARCHAR(128) NOT NULL DEFAULT '',
last_error TEXT NOT NULL,
created_at BIGINT NOT NULL,
delivered_at BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	},
	DialectPostgres: {
		`CREATE TABLE IF NOT EXISTS kkai_policy_incidents (
id BIGSERIAL PRIMARY KEY,
event_id VARCHAR(128) NOT NULL UNIQUE,
input_sha256 CHAR(64) NOT NULL,
source VARCHAR(32) NOT NULL,
occurred_at BIGINT NOT NULL,
request_id VARCHAR(64) NOT NULL DEFAULT '',
user_id INTEGER NOT NULL DEFAULT 0,
token_id INTEGER NOT NULL DEFAULT 0,
channel_id INTEGER NOT NULL DEFAULT 0,
model_name VARCHAR(128) NOT NULL DEFAULT '',
rule_version VARCHAR(64) NOT NULL DEFAULT '',
evidence_sha256 CHAR(64) NOT NULL,
token_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
upstream_key_fingerprint VARCHAR(80) NOT NULL DEFAULT '',
decision VARCHAR(32) NOT NULL,
metadata TEXT NOT NULL,
action_taken VARCHAR(255) NOT NULL DEFAULT '',
action_result VARCHAR(255) NOT NULL DEFAULT '',
token_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disabled BOOLEAN NOT NULL DEFAULT FALSE,
user_disable_skipped BOOLEAN NOT NULL DEFAULT FALSE,
channel_disabled BOOLEAN NOT NULL DEFAULT FALSE,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS kkai_outbox (
id BIGSERIAL PRIMARY KEY,
event_key VARCHAR(192) NOT NULL UNIQUE,
topic VARCHAR(128) NOT NULL,
aggregate_id VARCHAR(128) NOT NULL DEFAULT '',
payload TEXT NOT NULL,
status VARCHAR(16) NOT NULL,
attempts INTEGER NOT NULL DEFAULT 0,
available_at BIGINT NOT NULL,
locked_at BIGINT NOT NULL DEFAULT 0,
locked_by VARCHAR(128) NOT NULL DEFAULT '',
last_error TEXT NOT NULL,
created_at BIGINT NOT NULL,
delivered_at BIGINT NOT NULL DEFAULT 0
)`,
	},
}

var riskIndexes = []indexSpec{
	{Name: "idx_kkai_policy_incidents_occurred", Table: "kkai_policy_incidents", Columns: []string{"occurred_at"}},
	{Name: "idx_kkai_policy_incidents_request", Table: "kkai_policy_incidents", Columns: []string{"request_id"}},
	{Name: "idx_kkai_policy_incidents_user", Table: "kkai_policy_incidents", Columns: []string{"user_id"}},
	{Name: "idx_kkai_policy_incidents_token", Table: "kkai_policy_incidents", Columns: []string{"token_id"}},
	{Name: "idx_kkai_policy_incidents_channel", Table: "kkai_policy_incidents", Columns: []string{"channel_id"}},
	{Name: "idx_kkai_outbox_delivery", Table: "kkai_outbox", Columns: []string{"status", "available_at", "locked_at"}},
	{Name: "idx_kkai_outbox_topic", Table: "kkai_outbox", Columns: []string{"topic"}},
}
