package kkaimigrate

var imageStudioSchemaStatements = map[string][]migrationStatement{
	DialectSQLite: imageStudioStatements(
		"INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER", "BOOLEAN", "",
	),
	DialectMySQL: imageStudioStatements(
		"BIGINT AUTO_INCREMENT PRIMARY KEY", "INT", "BOOLEAN", " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
	),
	DialectPostgres: imageStudioStatements(
		"BIGSERIAL PRIMARY KEY", "INTEGER", "BOOLEAN", "",
	),
}

func imageStudioStatements(idType string, integerType string, booleanType string, tableSuffix string) []migrationStatement {
	return []migrationStatement{
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_image_model_profiles (
id ` + idType + `,
model VARCHAR(191) NOT NULL,
display_name VARCHAR(191) NOT NULL,
description TEXT NOT NULL,
provider_label VARCHAR(128) NOT NULL DEFAULT '',
specification_version ` + integerType + ` NOT NULL,
specification TEXT NOT NULL,
default_parameters TEXT NOT NULL,
enabled ` + booleanType + ` NOT NULL,
sort_order ` + integerType + ` NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)` + tableSuffix},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_image_model_profiles_model ON kkai_image_model_profiles (model)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_model_profiles_enabled_sort ON kkai_image_model_profiles (enabled, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_image_samples (
id ` + idType + `,
model_profile_id BIGINT NOT NULL,
image_asset_id BIGINT NOT NULL,
title VARCHAR(191) NOT NULL,
prompt TEXT NOT NULL,
model_version ` + integerType + ` NOT NULL,
parameters TEXT NOT NULL,
category VARCHAR(32) NOT NULL,
status VARCHAR(16) NOT NULL,
sort_order ` + integerType + ` NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)` + tableSuffix},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_samples_catalog ON kkai_image_samples (status, sort_order, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_samples_model ON kkai_image_samples (model_profile_id, status, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_image_generations (
id ` + idType + `,
user_id ` + integerType + ` NOT NULL,
token_id ` + integerType + ` NOT NULL,
model_profile_id BIGINT NOT NULL,
sample_id BIGINT,
specification_version ` + integerType + ` NOT NULL,
model VARCHAR(191) NOT NULL,
prompt TEXT NOT NULL,
parameters TEXT NOT NULL,
request_hash CHAR(64) NOT NULL,
request_id VARCHAR(64) NOT NULL,
status VARCHAR(24) NOT NULL,
requested_count ` + integerType + ` NOT NULL,
succeeded_count ` + integerType + ` NOT NULL DEFAULT 0,
final_quota ` + integerType + ` NOT NULL DEFAULT 0,
billing_source VARCHAR(16) NOT NULL DEFAULT '',
billing_state VARCHAR(16) NOT NULL DEFAULT 'pending',
reserved_quota ` + integerType + ` NOT NULL DEFAULT 0,
subscription_id ` + integerType + ` NOT NULL DEFAULT 0,
heartbeat_at BIGINT NOT NULL DEFAULT 0,
failure_stage VARCHAR(32) NOT NULL DEFAULT '',
error_code VARCHAR(64) NOT NULL DEFAULT '',
error_message VARCHAR(1024) NOT NULL DEFAULT '',
started_at BIGINT NOT NULL,
finished_at BIGINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)` + tableSuffix},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_image_generations_request ON kkai_image_generations (request_id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_generations_user ON kkai_image_generations (user_id, deleted_at, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_generations_reconcile ON kkai_image_generations (status, heartbeat_at, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_generations_billing ON kkai_image_generations (billing_state, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_image_assets (
id ` + idType + `,
generation_id BIGINT,
owner_user_id ` + integerType + ` NOT NULL DEFAULT 0,
scope VARCHAR(16) NOT NULL,
kind VARCHAR(16) NOT NULL,
state VARCHAR(16) NOT NULL,
position ` + integerType + ` NOT NULL DEFAULT 0,
object_key VARCHAR(191) NOT NULL,
thumbnail_object_key VARCHAR(191) NOT NULL DEFAULT '',
thumbnail_state VARCHAR(16) NOT NULL,
original_filename VARCHAR(255) NOT NULL DEFAULT '',
mime_type VARCHAR(128) NOT NULL,
size_bytes BIGINT NOT NULL DEFAULT 0,
width ` + integerType + ` NOT NULL DEFAULT 0,
height ` + integerType + ` NOT NULL DEFAULT 0,
sha256 CHAR(64) NOT NULL DEFAULT '',
failure_reason VARCHAR(1024) NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)` + tableSuffix},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_image_assets_object_key ON kkai_image_assets (object_key)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_image_assets_generation_position ON kkai_image_assets (generation_id, position)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_assets_owner_state ON kkai_image_assets (owner_user_id, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_image_assets_scope_kind ON kkai_image_assets (scope, kind, state, id)`},
	}
}
