package kkaimigrate

var videoStudioSchemaStatements = map[string][]migrationStatement{
	DialectSQLite: {
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_model_profiles (
id INTEGER PRIMARY KEY AUTOINCREMENT,
model VARCHAR(191) NOT NULL,
display_name VARCHAR(191) NOT NULL,
description TEXT NOT NULL,
provider_label VARCHAR(128) NOT NULL DEFAULT '',
specification_version INTEGER NOT NULL,
specification TEXT NOT NULL,
default_parameters TEXT NOT NULL,
enabled BOOLEAN NOT NULL,
sort_order INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_model_profiles_model ON kkai_video_model_profiles (model)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_model_profiles_enabled_sort ON kkai_video_model_profiles (enabled, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_samples (
id INTEGER PRIMARY KEY AUTOINCREMENT,
model_profile_id BIGINT NOT NULL,
title VARCHAR(191) NOT NULL,
prompt TEXT NOT NULL,
mode VARCHAR(32) NOT NULL,
model_version INTEGER NOT NULL,
parameters TEXT NOT NULL,
reference_asset_ids TEXT NOT NULL,
video_asset_id BIGINT NOT NULL,
aspect_ratio DOUBLE NOT NULL,
status VARCHAR(16) NOT NULL,
sort_order INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_catalog ON kkai_video_samples (status, sort_order, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_model ON kkai_video_samples (model_profile_id, status, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_generations (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
task_id BIGINT NOT NULL,
model_profile_id BIGINT NOT NULL,
sample_id BIGINT,
model VARCHAR(191) NOT NULL,
mode VARCHAR(32) NOT NULL,
prompt TEXT NOT NULL,
parameters TEXT NOT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_generations_task ON kkai_video_generations (task_id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_user ON kkai_video_generations (user_id, deleted_at, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_reconcile ON kkai_video_generations (deleted_at, id, task_id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_assets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
owner_user_id INTEGER NOT NULL DEFAULT 0,
scope VARCHAR(16) NOT NULL,
kind VARCHAR(16) NOT NULL,
state VARCHAR(24) NOT NULL,
object_key VARCHAR(191) NOT NULL,
poster_object_key VARCHAR(512) NOT NULL DEFAULT '',
preview_object_key VARCHAR(512) NOT NULL DEFAULT '',
archive_source_url TEXT NOT NULL,
original_filename VARCHAR(255) NOT NULL DEFAULT '',
mime_type VARCHAR(128) NOT NULL,
size_bytes BIGINT NOT NULL DEFAULT 0,
width INTEGER NOT NULL DEFAULT 0,
height INTEGER NOT NULL DEFAULT 0,
duration_seconds DOUBLE NOT NULL DEFAULT 0,
codec VARCHAR(64) NOT NULL DEFAULT '',
sha256 CHAR(64) NOT NULL DEFAULT '',
failure_reason VARCHAR(1024) NOT NULL DEFAULT '',
upload_mode VARCHAR(16) NOT NULL DEFAULT '',
multipart_upload_id VARCHAR(512) NOT NULL DEFAULT '',
upload_part_size BIGINT NOT NULL DEFAULT 0,
upload_expires_at BIGINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_assets_object_key ON kkai_video_assets (object_key)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_owner_state ON kkai_video_assets (owner_user_id, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_scope_kind ON kkai_video_assets (scope, kind, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_upload_expiry ON kkai_video_assets (upload_expires_at, id, state)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_task_assets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
task_id BIGINT NOT NULL,
asset_id BIGINT NOT NULL,
role VARCHAR(32) NOT NULL,
position INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_task_asset_role ON kkai_video_task_assets (task_id, role, position)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_task_assets_asset ON kkai_video_task_assets (asset_id, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_idempotency_keys (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
operation VARCHAR(64) NOT NULL,
"key" VARCHAR(128) NOT NULL,
request_hash CHAR(64) NOT NULL,
resource_type VARCHAR(32) NOT NULL DEFAULT '',
resource_id VARCHAR(128) NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
expires_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_idempotency_scope ON kkai_idempotency_keys (user_id, operation, "key")`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_idempotency_expiry ON kkai_idempotency_keys (expires_at, id)`},
	},
	DialectMySQL: {
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_model_profiles (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
model VARCHAR(191) NOT NULL,
display_name VARCHAR(191) NOT NULL,
description TEXT NOT NULL,
provider_label VARCHAR(128) NOT NULL DEFAULT '',
specification_version INT NOT NULL,
specification TEXT NOT NULL,
default_parameters TEXT NOT NULL,
enabled BOOLEAN NOT NULL,
sort_order INT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_model_profiles_model ON kkai_video_model_profiles (model)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_model_profiles_enabled_sort ON kkai_video_model_profiles (enabled, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_samples (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
model_profile_id BIGINT NOT NULL,
title VARCHAR(191) NOT NULL,
prompt TEXT NOT NULL,
mode VARCHAR(32) NOT NULL,
model_version INT NOT NULL,
parameters TEXT NOT NULL,
reference_asset_ids TEXT NOT NULL,
video_asset_id BIGINT NOT NULL,
aspect_ratio DOUBLE NOT NULL,
status VARCHAR(16) NOT NULL,
sort_order INT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_catalog ON kkai_video_samples (status, sort_order, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_model ON kkai_video_samples (model_profile_id, status, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_generations (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
task_id BIGINT NOT NULL,
model_profile_id BIGINT NOT NULL,
sample_id BIGINT,
model VARCHAR(191) NOT NULL,
mode VARCHAR(32) NOT NULL,
prompt TEXT NOT NULL,
parameters TEXT NOT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_generations_task ON kkai_video_generations (task_id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_user ON kkai_video_generations (user_id, deleted_at, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_reconcile ON kkai_video_generations (deleted_at, id, task_id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_assets (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
owner_user_id INT NOT NULL DEFAULT 0,
scope VARCHAR(16) NOT NULL,
kind VARCHAR(16) NOT NULL,
state VARCHAR(24) NOT NULL,
object_key VARCHAR(191) NOT NULL,
poster_object_key VARCHAR(512) NOT NULL DEFAULT '',
preview_object_key VARCHAR(512) NOT NULL DEFAULT '',
archive_source_url TEXT NOT NULL,
original_filename VARCHAR(255) NOT NULL DEFAULT '',
mime_type VARCHAR(128) NOT NULL,
size_bytes BIGINT NOT NULL DEFAULT 0,
width INT NOT NULL DEFAULT 0,
height INT NOT NULL DEFAULT 0,
duration_seconds DOUBLE NOT NULL DEFAULT 0,
codec VARCHAR(64) NOT NULL DEFAULT '',
sha256 CHAR(64) NOT NULL DEFAULT '',
failure_reason VARCHAR(1024) NOT NULL DEFAULT '',
upload_mode VARCHAR(16) NOT NULL DEFAULT '',
multipart_upload_id VARCHAR(512) NOT NULL DEFAULT '',
upload_part_size BIGINT NOT NULL DEFAULT 0,
upload_expires_at BIGINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_assets_object_key ON kkai_video_assets (object_key)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_owner_state ON kkai_video_assets (owner_user_id, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_scope_kind ON kkai_video_assets (scope, kind, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_upload_expiry ON kkai_video_assets (upload_expires_at, id, state)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_task_assets (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
task_id BIGINT NOT NULL,
asset_id BIGINT NOT NULL,
role VARCHAR(32) NOT NULL,
position INT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_task_asset_role ON kkai_video_task_assets (task_id, role, position)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_task_assets_asset ON kkai_video_task_assets (asset_id, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_idempotency_keys (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
operation VARCHAR(64) NOT NULL,
` + "`key`" + ` VARCHAR(128) NOT NULL,
request_hash CHAR(64) NOT NULL,
resource_type VARCHAR(32) NOT NULL DEFAULT '',
resource_id VARCHAR(128) NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
expires_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`},
		{Operation: migrationOperationCreateIndex, SQL: "CREATE UNIQUE INDEX ux_kkai_idempotency_scope ON kkai_idempotency_keys (user_id, operation, `key`)"},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_idempotency_expiry ON kkai_idempotency_keys (expires_at, id)`},
	},
	DialectPostgres: {
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_model_profiles (
id BIGSERIAL PRIMARY KEY,
model VARCHAR(191) NOT NULL,
display_name VARCHAR(191) NOT NULL,
description TEXT NOT NULL,
provider_label VARCHAR(128) NOT NULL DEFAULT '',
specification_version INTEGER NOT NULL,
specification TEXT NOT NULL,
default_parameters TEXT NOT NULL,
enabled BOOLEAN NOT NULL,
sort_order INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_model_profiles_model ON kkai_video_model_profiles (model)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_model_profiles_enabled_sort ON kkai_video_model_profiles (enabled, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_samples (
id BIGSERIAL PRIMARY KEY,
model_profile_id BIGINT NOT NULL,
title VARCHAR(191) NOT NULL,
prompt TEXT NOT NULL,
mode VARCHAR(32) NOT NULL,
model_version INTEGER NOT NULL,
parameters TEXT NOT NULL,
reference_asset_ids TEXT NOT NULL,
video_asset_id BIGINT NOT NULL,
aspect_ratio DOUBLE PRECISION NOT NULL,
status VARCHAR(16) NOT NULL,
sort_order INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_catalog ON kkai_video_samples (status, sort_order, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_samples_model ON kkai_video_samples (model_profile_id, status, sort_order, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_generations (
id BIGSERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
task_id BIGINT NOT NULL,
model_profile_id BIGINT NOT NULL,
sample_id BIGINT,
model VARCHAR(191) NOT NULL,
mode VARCHAR(32) NOT NULL,
prompt TEXT NOT NULL,
parameters TEXT NOT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_generations_task ON kkai_video_generations (task_id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_user ON kkai_video_generations (user_id, deleted_at, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_generations_reconcile ON kkai_video_generations (deleted_at, id, task_id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_assets (
id BIGSERIAL PRIMARY KEY,
owner_user_id INTEGER NOT NULL DEFAULT 0,
scope VARCHAR(16) NOT NULL,
kind VARCHAR(16) NOT NULL,
state VARCHAR(24) NOT NULL,
object_key VARCHAR(191) NOT NULL,
poster_object_key VARCHAR(512) NOT NULL DEFAULT '',
preview_object_key VARCHAR(512) NOT NULL DEFAULT '',
archive_source_url TEXT NOT NULL,
original_filename VARCHAR(255) NOT NULL DEFAULT '',
mime_type VARCHAR(128) NOT NULL,
size_bytes BIGINT NOT NULL DEFAULT 0,
width INTEGER NOT NULL DEFAULT 0,
height INTEGER NOT NULL DEFAULT 0,
duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
codec VARCHAR(64) NOT NULL DEFAULT '',
sha256 CHAR(64) NOT NULL DEFAULT '',
failure_reason VARCHAR(1024) NOT NULL DEFAULT '',
upload_mode VARCHAR(16) NOT NULL DEFAULT '',
multipart_upload_id VARCHAR(512) NOT NULL DEFAULT '',
upload_part_size BIGINT NOT NULL DEFAULT 0,
upload_expires_at BIGINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
deleted_at BIGINT NOT NULL DEFAULT 0
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_assets_object_key ON kkai_video_assets (object_key)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_owner_state ON kkai_video_assets (owner_user_id, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_scope_kind ON kkai_video_assets (scope, kind, state, id)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_assets_upload_expiry ON kkai_video_assets (upload_expires_at, id, state)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_video_task_assets (
id BIGSERIAL PRIMARY KEY,
task_id BIGINT NOT NULL,
asset_id BIGINT NOT NULL,
role VARCHAR(32) NOT NULL,
position INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_video_task_asset_role ON kkai_video_task_assets (task_id, role, position)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_video_task_assets_asset ON kkai_video_task_assets (asset_id, id)`},
		{Operation: migrationOperationCreateTable, SQL: `CREATE TABLE IF NOT EXISTS kkai_idempotency_keys (
id BIGSERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
operation VARCHAR(64) NOT NULL,
"key" VARCHAR(128) NOT NULL,
request_hash CHAR(64) NOT NULL,
resource_type VARCHAR(32) NOT NULL DEFAULT '',
resource_id VARCHAR(128) NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
expires_at BIGINT NOT NULL
)`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE UNIQUE INDEX ux_kkai_idempotency_scope ON kkai_idempotency_keys (user_id, operation, "key")`},
		{Operation: migrationOperationCreateIndex, SQL: `CREATE INDEX idx_kkai_idempotency_expiry ON kkai_idempotency_keys (expires_at, id)`},
	},
}
